name = "ncr-watchdog-dashboard"
compatibility_date = "2026-05-27"
pages_build_output_dir = "dist/public"

[vars]
FRONTEND_URL = "https://ncr-watchdog-dashboard.pages.dev/"
DASHBOARD_URL = "https://ncr-watchdog-dashboard.pages.dev/"
ALLOWED_ORIGINS = "https://ncr-watchdog-dashboard.pages.dev,https://ncr-watchdog-dashboard.pages.dev/"
VITE_API_BASE_URL = "https://ncr-watchdog-dashboard.pages.dev"
BACKEND_ORIGIN = "http://35.196.168.113.sslip.io:3000"
TELEGRAM_CHAT_ID = "8855631169,8674647124,8216202664"
TELEGRAM_AUTHORIZED_CHAT_IDS = "8855631169,8674647124,8216202664"
